---
- hosts: all
  become: true
  vars:
    docker_compose_version: "1.27.4"
  tasks:
  - debug:
      var: ansible_os_family
      
  - name: "create yum repository for docker"
    yum_repository:
      name: docker-repo
      description: "repo for docker"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes
      gpgcheck: no
    when: ansible_facts['os_family'] == 'RedHat'
  
  - name: "Install docker"
    package: 
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "Install pip"
    package: 
      name: "python3-pip"
      state: present
      update_cache: true
    
  - name: "Install docker sdk"
    pip:
     name: "docker"
 
  # - name: "Update docker service"
  #   replace:
  #      path: "/lib/systemd/system/docker.service"
  #      regexp: "^ExecStart.*"
  #      replace: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243"
  #   notify: 
  #   - "Restart docker"
  #   - "Reload deamon"
  
  - name: "Start docker service"
    service:
      name: "docker"
      state: started

  - name: Download docker-compose {{ docker_compose_version }}
    get_url:
      url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: ~/docker-compose
      mode: '+x'

  - name: Check docker-compose exists 
    stat: path=~/docker-compose
    register: docker_compose

  - name: Move docker-compose to /usr/local/bin/docker-compose
    command: mv ~/docker-compose /usr/local/bin/docker-compose
    when: docker_compose.stat.exists

  # handlers:
  # - name: "Restart docker"
  #   service:
  #      name: "docker"
  #      state: restarted

  # - name: "Reload deamon"
  #   systemd:
  #      daemon_reload: yes
